name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@master

      # CMake needs to be updated only on ubuntu unfortunately, github recently updated the version on macOS and Windows, need to wait for ubuntu
      - name: download latest cmake - Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo rm -rf /usr/local/bin/cmake
          sudo curl -L https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.tar.gz -o /tmp/cmake.tar.gz
          sudo tar -xf /tmp/cmake.tar.gz --directory /tmp
          sudo cp /tmp/cmake*/bin/cmake /usr/local/bin/cmake
          sudo cp -R /tmp/cmake*/share/cmake-3.15 /usr/local/share/cmake-3.15

      - name: configure
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cd build && cmake --build . --config Release -- -j 8

      - uses: actions/upload-artifact@master
        with:
          name: binaries
          path: dist/bin